name: GitHub Release Creation

# 只有当一个新的 Git Tag（例如 v1.1）被推送到 GitHub 时，才触发此工作流。
on:
  push:
    tags:
      - 'v*' # 匹配所有以 'v' 开头的标签，如 v1.0, v1.1, v2

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        # 检出代码是必要的，因为 actions/create-release 需要访问仓库。
        uses: actions/checkout@v4
        
      - name: Extract Tag Version
        # 提取当前推送的 Git Tag 作为版本号 (e.g., v1.1)
        id: meta
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        # 使用 actions/create-release V1 版本创建正式的 Release 页面。
        # GITHUB_TOKEN 是 GitHub Actions 自动提供的权限 token，用于操作当前仓库。
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          release_name: Release ${{ steps.meta.outputs.tag }}
          # 默认为 false，表示发布正式版本而不是草稿或预发布版本。
          draft: false
          prerelease: false
